# Generated by Django 4.0.6 on 2022-07-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_usersmodel_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersmodel',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='staff status'),
        ),
    ]
